management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      resilience4j.retry: true


resilience4j:
  circuitbreaker:
    instances:
      ServiceCircuitBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED


  retry:
    instances:
      ServiceRetry:
        maxAttempts: 2
        waitDuration: 10s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2











